syntax = "proto3";

package quilt;

service QuiltService {
  rpc GetNodeNetworking(GetNodeNetworkingRequest) returns (GetNodeNetworkingResponse);
  rpc UpsertHostRoute(UpsertHostRouteRequest) returns (UpsertHostRouteResponse);
  rpc DeleteHostRoute(DeleteHostRouteRequest) returns (DeleteHostRouteResponse);
}

message GetNodeNetworkingRequest {}

message GetNodeNetworkingResponse {
  bool success = 1;
  string error = 2;
  string pod_cidr = 3;
  string bridge_name = 4;
  string bridge_ip = 5;
  uint32 dns_port = 6;
}

message UpsertHostRouteRequest {
  string destination = 1;
  string via_interface = 2;
}

message UpsertHostRouteResponse {
  bool success = 1;
  string error = 2;
}

message DeleteHostRouteRequest {
  string destination = 1;
}

message DeleteHostRouteResponse {
  bool success = 1;
  string error = 2;
}
